### ISSUE TITLE
Transfer never finishes

### ISSUE THREAD

**Issue by hmrc87** [thrashr888/grunt-sftp-deploy#74]
Hi, I have setup sftp-deploy and it uploads all my files but stops like this:

 transferred=[98/101] elapsed=[8.3s] overall=[97%] eta=[0.3s] [======================================= ] done
 transferred=[99/101] elapsed=[8.4s] overall=[98%] eta=[0.2s] [======================================= ]

and then it does not continue other tasks.

/e: I had three video files with around 5MB in my folder. After I deleted them locally the transfer worked!

**Comment by doodirock** [comment]
Same issue.  Would love to get this to work but it fails every time.  Actually i guess it doesnt fail, just sits there and never finishes.

 transferred=[1/10] elapsed=[0.0s] overall=[10%] eta=[0.0s] [==               ]
 >> Directories done.
 transferred=[8/10] elapsed=[1.4s] overall=[80%] eta=[0.4s] [==============   ]

**Comment by flaurian** [comment]
+1

**Comment by mamarmite** [comment]
Got same behavior as @Hmarc187 . Alway stuck at 2 elements stop from being uploaded on 2000 elements.
I have to stop the behavior (ctrl+c windows 8.1). The cache never save the current state too.

But I don't have in the project big files to sent. It's almost all scripts and images.

Is their a more verbose option? I just don't know where to start to debug.

**Comment by langersteff** [comment]
Settings `concurrency: 1` fixes it for me.

**Comment by streamer** [comment]
Same problem... 
concurrency: 1 
does not help!

**Comment by langersteff** [comment]
I switched to rsync for deploying, which makes it wayyyy faster.

**Comment by amitgur** [comment]
same problem in 2020. moved to rsync

**Comment by mamarmite** [comment]
I moved to a git based deployment now :)
