### ISSUE TITLE
Publish changes to NPM

### ISSUE THREAD

**Issue by johnhaley81** [thrashr888/grunt-sftp-deploy#81]
Getting the changes from https://github.com/thrashr888/grunt-sftp-deploy/commit/27684413880357535acc89e72f244677596b6462 into a published version on NPM would be
:ok_hand::eyes::ok_hand::eyes::ok_hand::eyes::ok_hand::eyes::ok_hand::eyes: good shit go౦ԁ sHit:ok_hand: thats :heavy_check_mark: some good:ok_hand::ok_hand:shit right:ok_hand::ok_hand:there:ok_hand::ok_hand::ok_hand: right:heavy_check_mark:there :heavy_check_mark::heavy_check_mark:if i do ƽaү so my self :100: i say so :100: thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ:100: :ok_hand::ok_hand: :ok_hand:НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ:ok_hand: :ok_hand::ok_hand: :ok_hand: :100: :ok_hand: :eyes: :eyes: :eyes: :ok_hand::ok_hand:Good shit

**Comment by thrashr888** [comment]
Wow. Okay. I'll do that soon.

**Comment by thrashr888** [comment]
Done!

**Comment by johnhaley81** [comment]
<3
